// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkyycxmhkwwqxlwcisph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreXljeG1oa3d3cXhsd2Npc3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTkxMDAsImV4cCI6MjA3MTc3NTEwMH0.FOeO2Veyk4neYVOmbxWJ6ON_x4_6nT1pWr5Hkr2GqTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});